In [82]:
!pip install --pre pycaret
!pip install mlxtend --upgrade --no-deps

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.3 MB 9.9 MB/s 
  Attempting uninstall: mlxtend
    Found existing installation: mlxtend 0.14.0
    Uninstalling mlxtend-0.14.0:
      Successfully uninstalled mlxtend-0.14.0


In [1]:
#loading dataset
import pandas as pd
import numpy as np
#visualisation
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
#EDA
from collections import Counter
# data preprocessing
from sklearn.preprocessing import StandardScaler
# data splitting
from sklearn.model_selection import train_test_split
# data modeling
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
#ensembling
from mlxtend.classifier import StackingCVClassifier

In [2]:
df = pd.read_csv('heart.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [4]:
df.shape

(1025, 14)

In [5]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
df.describe().T

count        mean        std    min    25%    50%    75%    max
age       1025.0   54.434146   9.072290   29.0   48.0   56.0   61.0   77.0
sex       1025.0    0.695610   0.460373    0.0    0.0    1.0    1.0    1.0
cp        1025.0    0.942439   1.029641    0.0    0.0    1.0    2.0    3.0
trestbps  1025.0  131.611707  17.516718   94.0  120.0  130.0  140.0  200.0
chol      1025.0  246.000000  51.592510  126.0  211.0  240.0  275.0  564.0
fbs       1025.0    0.149268   0.356527    0.0    0.0    0.0    0.0    1.0
restecg   1025.0    0.529756   0.527878    0.0    0.0    1.0    1.0    2.0
thalach   1025.0  149.114146  23.005724   71.0  132.0  152.0  166.0  202.0
exang     1025.0    0.336585   0.472772    0.0    0.0    0.0    1.0    1.0
oldpeak   1025.0    1.071512   1.175053    0.0    0.0    0.8    1.8    6.2
slope     1025.0    1.385366   0.617755    0.0    1.0    1.0    2.0    2.0
ca        1025.0    0.754146   1.030798    0.0    0.0    0.0    1.0    4.0
thal      1025.0    2.323902   0.620660    0.0    2.0    2.0    3.0    3.0
target    1025.0    0.513171   0.500070    0.0    0.0    1.0    1.0    1.0

In [7]:
from pycaret.classification import *
s = setup(df, target = 'target')

In [8]:
best = compare_models()

Processing:   0%|          | 0/61 [00:00<?, ?it/s]

In [9]:
predict_model(best)

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
717   67.0  1.0  0.0     120.0  229.0  0.0      0.0    129.0    1.0      2.6   
718   71.0  0.0  2.0     110.0  265.0  1.0      0.0    130.0    0.0      0.0   
719   59.0  1.0  3.0     160.0  273.0  0.0      0.0    125.0    0.0      0.0   
720   57.0  1.0  1.0     154.0  232.0  0.0      0.0    164.0    0.0      0.0   
721   58.0  1.0  2.0     140.0  211.0  1.0      0.0    165.0    0.0      0.0   
...    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
1020  57.0  1.0  0.0     165.0  289.0  1.0      0.0    124.0    0.0      1.0   
1021  50.0  1.0  2.0     140.0  233.0  0.0      1.0    163.0    0.0      0.6   
1022  60.0  0.0  3.0     150.0  240.0  0.0      1.0    171.0    0.0      0.9   
1023  45.0  1.0  0.0     115.0  260.0  0.0      0.0    185.0    0.0      0.0   
1024  66.0  1.0  0.0     160.0  228.0  0.0      0.0    138.0    0.0      2.3   

      slope   ca  thal  target  prediction_label  prediction_score  
717     1.0  2.0   3.0       0                 0              1.00  
718     2.0  1.0   2.0       1                 1              0.99  
719     2.0  0.0   2.0       0                 0              0.91  
720     2.0  1.0   2.0       0                 0              0.90  
721     2.0  0.0   2.0       1                 1              0.99  
...     ...  ...   ...     ...               ...               ...  
1020    1.0  3.0   3.0       0                 0              1.00  
1021    1.0  1.0   3.0       0                 0              0.74  
1022    2.0  0.0   2.0       1                 1              0.97  
1023    2.0  0.0   2.0       1                 1              0.98  
1024    2.0  0.0   1.0       1                 1              0.92  

[308 rows x 16 columns]

In [10]:
best

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=4498, verbose=0, warm_start=False)

In [62]:
np.random.seed(0)
y = df["target"]
X = df.drop('target',axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [63]:
print(y_test.unique())
Counter(y_train)

[1 0]


Counter({1: 363, 0: 354})

In [64]:
m1 = 'Extra Trees Classifier'
et = ExtraTreesClassifier(random_state=0)
et.fit(X_train,y_train)
et_predicted = et.predict(X_test)
et_conf_matrix = confusion_matrix(y_test, et_predicted)
et_acc_score = accuracy_score(y_test, et_predicted)
print("confussion matrix")
print(et_conf_matrix)
print("\n")
print("Accuracy of Extra Trees Classifier:",et_acc_score*100,'\n')
print(classification_report(y_test,et_predicted))

confussion matrix
[[145   0]
 [  0 163]]


Accuracy of Extra Trees Classifier: 100.0 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       145
           1       1.00      1.00      1.00       163

    accuracy                           1.00       308
   macro avg       1.00      1.00      1.00       308
weighted avg       1.00      1.00      1.00       308



In [65]:
m2 = 'Random Forest Classfier'
rf = RandomForestClassifier(random_state=0)
rf.fit(X_train,y_train)
rf_predicted = rf.predict(X_test)
rf_conf_matrix = confusion_matrix(y_test, rf_predicted)
rf_acc_score = accuracy_score(y_test, rf_predicted)
print("confussion matrix")
print(rf_conf_matrix)
print("\n")
print("Accuracy of Random Forest:",rf_acc_score*100,'\n')
print(classification_report(y_test,rf_predicted))

confussion matrix
[[145   0]
 [  0 163]]


Accuracy of Random Forest: 100.0 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       145
           1       1.00      1.00      1.00       163

    accuracy                           1.00       308
   macro avg       1.00      1.00      1.00       308
weighted avg       1.00      1.00      1.00       308



In [66]:
m3 = 'Random Forest Classfier'
gbc = GradientBoostingClassifier(random_state=0)
gbc.fit(X_train,y_train)
gbc_predicted = gbc.predict(X_test)
gbc_conf_matrix = confusion_matrix(y_test, gbc_predicted)
gbc_acc_score = accuracy_score(y_test, gbc_predicted)
print("confussion matrix")
print(gbc_conf_matrix)
print("\n")
print("Accuracy of Random Forest:",gbc_acc_score*100,'\n')
print(classification_report(y_test,gbc_predicted))

confussion matrix
[[140   5]
 [  2 161]]


Accuracy of Random Forest: 97.72727272727273 

              precision    recall  f1-score   support

           0       0.99      0.97      0.98       145
           1       0.97      0.99      0.98       163

    accuracy                           0.98       308
   macro avg       0.98      0.98      0.98       308
weighted avg       0.98      0.98      0.98       308



In [67]:
scv=StackingCVClassifier(classifiers=[et,rf,gbc],meta_classifier=et, random_state=0)
scv.fit(X_train,y_train)
scv_predicted = scv.predict(X_test)
scv_conf_matrix = confusion_matrix(y_test, scv_predicted)
scv_acc_score = accuracy_score(y_test, scv_predicted)
print("confussion matrix")
print(scv_conf_matrix)
print("\n")
print("Accuracy of StackingCVClassifier:",scv_acc_score*100,'\n')
print(classification_report(y_test,scv_predicted))

confussion matrix
[[145   0]
 [  0 163]]


Accuracy of StackingCVClassifier: 100.0 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       145
           1       1.00      1.00      1.00       163

    accuracy                           1.00       308
   macro avg       1.00      1.00      1.00       308
weighted avg       1.00      1.00      1.00       308

